name: TypeScript

on:
  push:
    branches:
      - next
    paths:
    - '**.ts'
  pull_request:
    paths:
    - '**.ts'
  workflow_dispatch:

jobs:
  tsc:
    name: "TSC"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "npm"
    - run: npm install
    - run: npx tsc --noEmit
  eslint:
    name: "eslint"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "npm"
    - run: npm install
    - run: npx eslint .
  javascript_sync:
    name: "Check for outdated JavaScript"
    needs: tsc
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "npm"
    - run: npm install
    - run: rm -rf files/js/SoftCreatR/
    - run: rm -rf files/js/MysteryCode/
    - run: npx tsc
    - run: echo "::add-matcher::.github/diff.json"
    - name: Show diff
      run: |
        git checkout -- package-lock.json
        git diff --exit-code
